# These restrictions are sent to all players connecting to the server
# Restrictions with false values are not sent, if you want to send a false value change to "force-false"
# example:
#   no_xray: force-false
# You can add extra restriction names in case they are added after the creation of this plugin
#
# You can toggle restrictions per player by API
default-restrictions:
  # Show suffocation screen when in solid block
  no_xray: false

  # Disable the ability to fly through blocks
  no_noclip: false

  # The camera may not leave the first person view (this should be used with no_xray in case the player clips into blocks)
  only_first_person: false

  # Same as only_first_person except that changing the view to another player is also forbidden
  only_recording_player: false

  # Hides the coordinates from the F3 screen
  hide_coordinates: false